# This is a basic workflow to help you get started with Actions

name: List Organization repository Details

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Fetch all repos in organization 
        env: # Or as an environment variable
          github_token: ${{ secrets.LOCAL_GITHUB_TOKEN }}
          organization: ${{ secrets.ORG_NAME }}
        run: |
          chmod +x list_org_repos.sh
          ./list_org_repos.sh

      # Creats a csv artifact containg the repo details
      - name: upload organization repository details
        uses: actions/upload-artifact@v2.2.4
        with:
          name: oraganization_repository_details.csv
          path: oraganization_repository_details.csv